/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Dulana
 */
public class issueuser extends javax.swing.JFrame {

    /**
     * Creates new form issueuser
     */
    Connection con = null;
    Statement stmt = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    public issueuser() {
        initComponents();
        con = database_connection.connection();
        bookid ();
        stuid ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void bookid (){
       String sql = "SELECT * from newbook"; 
       try{
           pst = con.prepareStatement(sql);
           rs = pst.executeQuery();
           
           while(rs.next())
                   {
                     txtbookid.addItem(rs.getString("bookid"));
                   }
       }
       catch(Exception e){
           
           
       }
    }
    
    
    private void stuid (){
       String sql = "SELECT * from student"; 
       try{
           pst = con.prepareStatement(sql);
           rs = pst.executeQuery();
           
           while(rs.next())
                   {
                     txtstuid.addItem(rs.getString("regnumber"));
                   }
       }
       catch(Exception e){
           
           
       }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        duedate = new com.toedter.calendar.JDateChooser();
        issuedate = new com.toedter.calendar.JDateChooser();
        txtstuid = new javax.swing.JComboBox<>();
        txtbookid = new javax.swing.JComboBox<>();
        txtbook = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 120, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 120, 40));
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 160, 30));
        getContentPane().add(issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 160, 30));

        txtstuid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        getContentPane().add(txtstuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 160, 30));

        txtbookid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        txtbookid.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                txtbookidPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 160, 30));
        getContentPane().add(txtbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagment/issuebkuser_2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        new homeuser().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         for (double i = 0.0; i<=1.0; i = i + 0.1)
        {
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                
               Thread.sleep(50);
            }
            catch(Exception e)
            {
                
            }
        }

    }//GEN-LAST:event_formWindowOpened

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // Issue
        
        
        try{
            stmt =con.createStatement();
         SimpleDateFormat dFormat = new SimpleDateFormat ("dd-MM-yyyy");
        String bookID = txtbookid.getSelectedItem().toString();
        String BookName = txtbook.getText();
        String Studentid = txtstuid.getSelectedItem().toString();
        
        String issueDate = dFormat.format(issuedate.getDate());
        String dueDate = dFormat.format(duedate.getDate());
        String returnbook = "NO";
        
       String query = "INSERT INTO issuebook (bookid,bookname,studentid,issuedate,duedate,returnbook) VALUES(?,?,?,?,?,?)";
        
       PreparedStatement  pst = con.prepareStatement(query);
        
        pst.setString(1, bookID);
        pst.setString(2, BookName);
        pst.setString(3, Studentid);
        pst.setString(4, issueDate);
        pst.setString(5, dueDate);
        pst.setString(6, returnbook);
        
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "Book Issued");
        
        txtbookid.setSelectedIndex(0);
        txtstuid.setSelectedIndex(0);
        txtbook.setText(null);
        issuedate.setCalendar(null);
        duedate.setCalendar(null);
        
        
        }
        catch(Exception e){
             System.out.print(e);
        }
        
                
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtbookidPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_txtbookidPopupMenuWillBecomeInvisible
        String ID =txtbookid.getSelectedItem().toString();
        String sql = "SELECT * FROM newbook WHERE bookid =?";
        
       
            try{
            pst = con.prepareStatement(sql);
            pst .setString(1, ID);
            rs = pst .executeQuery();
            
            if(rs.next()){
                String name = rs.getString("bookname");
                txtbook.setText(name);
               
                
                
                
         
            }
            
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_txtbookidPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issueuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issueuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issueuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issueuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issueuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser duedate;
    private com.toedter.calendar.JDateChooser issuedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtbook;
    private javax.swing.JComboBox<String> txtbookid;
    private javax.swing.JComboBox<String> txtstuid;
    // End of variables declaration//GEN-END:variables
}
