/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dulana
 */
public class newstuser extends javax.swing.JFrame {

    /**
    
     */
    Connection con = null;
    Statement stmt = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    public newstuser() {
        initComponents();
         initComponents();
        con = database_connection.connection();
        tabledata();
    }

     private void Reset(){
             txtbookid.setText("");
            txtbookname.setText("");
            txtpublisher.setText("");
            txtpubyear.setText("");
            txtprice.setText("");
        }
     
      private void tabledata()
    {
        try{
            con = database_connection.connection();
            stmt = con.createStatement();
           
                String query = "SELECT * FROM newbook";
                rs = stmt.executeQuery(query);
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "connection error");
        }
        
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtprice = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtpublisher = new javax.swing.JTextField();
        txtpubyear = new javax.swing.JTextField();
        delete = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 150, 30));
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 150, 30));
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 150, 30));
        getContentPane().add(txtpublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 150, 30));
        getContentPane().add(txtpubyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 150, 30));

        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 90, 30));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 90, 30));

        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagment/viewbookuser.JPG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         for (double i = 0.0; i<=1.0; i = i + 0.1)
        {
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                
               Thread.sleep(50);
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
         try
        {
            stmt = con.createStatement();
            int Bookid = Integer.parseInt(txtbookid.getText());
            String Bookname= txtbookname.getText();
            String Publisher = txtpublisher.getText();
            String Publishyear= txtpubyear.getText();
            int Price = Integer.parseInt(txtprice.getText());
            
           
            
            String query = "UPDATE newbook SET  bookname=?, Publisher=?, PublisherYear=?, Price=? WHERE bookid=? ";
          
            PreparedStatement prepareStmp = con.prepareStatement(query);
            
            
            
            prepareStmp.setString(1, Bookname);
            prepareStmp.setString(2, Publisher);
            prepareStmp.setString(3, Publishyear);
            prepareStmp.setInt(4, Price);
            prepareStmp.setInt(5, Bookid);
            
            
            
            
            prepareStmp.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Updated");
            tabledata();
            
            Reset();
            
        
        }
        catch(Exception e)
        {
            
            System.out.print(e);
        
        }
    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
           try
        {
            stmt = con.createStatement();
            
            int Id = Integer.parseInt(txtbookid.getText());
           // int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
            String query = "DELETE FROM newbook WHERE bookid = '"+Id+"' ";
            
                 
            stmt.executeUpdate(query);
            tabledata();
            JOptionPane.showMessageDialog(null, "Record Deleted!!");
            Reset();
            
            
              
        
        }
        catch(Exception e)
        {
            System.out.print(e);
        
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       this.dispose();
        new homeuser().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newstuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newstuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newstuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newstuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newstuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtpublisher;
    private javax.swing.JTextField txtpubyear;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
