/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dulana
 */
public class returnbook extends javax.swing.JFrame {

    /**
     * Creates new form returnbook
     */
    Connection con = null;
    Statement stmp = null;
    ResultSet rs = null;
    PreparedStatement prepareStmp;
    public returnbook() {
        initComponents();
        con = database_connection.connection();
        bookid ();
    }
 private void Reset(){
        txtbookid.setSelectedIndex(0);
        txtbookname.setText("");
        txtstuid.setText("");
        txtissue.setText("");
        txtdue.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtdue = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtstuid = new javax.swing.JTextField();
        txtissue = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Due Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Book Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Student ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Issue Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 100, 30));

        txtdue.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtdue, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 180, 40));

        txtbookname.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 180, 40));

        txtstuid.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtstuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 180, 40));

        txtissue.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 180, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dulana\\Downloads\\Icon 1\\Icon 1\\red-x-mark-transparent-background-3.png")); // NOI18N
        jButton2.setText("Close");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 120, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dulana\\Downloads\\Icon 1\\Icon 1\\return book png.png")); // NOI18N
        jButton3.setText("Return");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 130, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Book ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 80, 30));

        txtbookid.setBackground(new java.awt.Color(255, 255, 204));
        txtbookid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        txtbookid.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                txtbookidPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagment/return book.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         for (double i = 0.0; i<=1.0; i = i + 0.1)
        {
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                
               Thread.sleep(50);
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void bookid (){
       String sql = "SELECT * from issuebook"; 
       try{
           prepareStmp = con.prepareStatement(sql);
           rs = prepareStmp.executeQuery();
           
           while(rs.next())
                   {
                     txtbookid.addItem(rs.getString("bookid"));
                   }
       }
       catch(Exception e){
           
       }
    }
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void txtbookidPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_txtbookidPopupMenuWillBecomeInvisible
         String ID =txtbookid.getSelectedItem().toString();
        String sql = "SELECT * FROM issuebook WHERE bookid =?";
        
       
            try{
            prepareStmp = con.prepareStatement(sql);
            prepareStmp.setString(1, ID);
            rs = prepareStmp.executeQuery();
            
            if(rs.next()){
                String STid = rs.getString("studentid");
                txtstuid.setText(STid);
                
                String BookName = rs.getString("bookname");
                txtbookname.setText(BookName);
               
                String issueID = rs.getString("issuedate");
                txtissue.setText(issueID);
                String DueDate = rs.getString("duedate");
                txtdue.setText(DueDate);
                
                
         
            }
            
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_txtbookidPopupMenuWillBecomeInvisible

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try
        {
            stmp = con.createStatement();
            String bookID = txtbookid.getSelectedItem().toString();
            String StID = txtstuid.getText();
            //String IssuDate = issue
            //String returnBook = "YES";
           
            String query = "UPDATE issuebook SET returnbook='YES' WHERE bookid=? and studentid=? ";
          
            PreparedStatement prepareStmp = con.prepareStatement(query);
            
            
            prepareStmp.setString(1, bookID);
            prepareStmp.setString(2, StID);
            
            
           
            
            prepareStmp.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "The Book has Returned !!");
            
            Reset();
        
        }
        catch(Exception e)
        {
            
            System.out.print(e);
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtdue;
    private javax.swing.JTextField txtissue;
    private javax.swing.JTextField txtstuid;
    // End of variables declaration//GEN-END:variables
}
