/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dulana
 */
public class returnuser extends javax.swing.JFrame {

    /**
     * Creates new form returnuser
     */
     Connection con = null;
    Statement stmp = null;
    ResultSet rs = null;
    PreparedStatement prepareStmp;
    public returnuser() {
        initComponents();
         con = database_connection.connection();
        bookid ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
     private void bookid (){
       String sql = "SELECT * from issuebook"; 
       try{
           prepareStmp = con.prepareStatement(sql);
           rs = prepareStmp.executeQuery();
           
           while(rs.next())
                   {
                     bookid.addItem(rs.getString("bookid"));
                   }
       }
       catch(Exception e){
           
           
       }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dueid = new javax.swing.JTextField();
        stid = new javax.swing.JTextField();
        txtissue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bookid = new javax.swing.JComboBox<>();
        txtbookname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dueid.setBackground(new java.awt.Color(255, 255, 153));
        dueid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(dueid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 180, 40));

        stid.setBackground(new java.awt.Color(255, 255, 153));
        stid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(stid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 180, 40));

        txtissue.setBackground(new java.awt.Color(255, 255, 153));
        txtissue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(txtissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 180, 40));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 120, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 120, 40));

        bookid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bookid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        bookid.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                bookidPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 180, 40));

        txtbookname.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagment/returnbkuser_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       this.dispose();
        new homeuser().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i<=1.0; i = i + 0.1)
        {
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                
               Thread.sleep(50);
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void bookidPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_bookidPopupMenuWillBecomeInvisible
        
        String ID =bookid.getSelectedItem().toString();
        String sql = "SELECT * FROM issuebook WHERE bookid =?";
        
       
            try{
            prepareStmp = con.prepareStatement(sql);
            prepareStmp.setString(1, ID);
            rs = prepareStmp.executeQuery();
            
            if(rs.next()){
                String STid = rs.getString("studentid");
                stid.setText(STid);
                
                String BookName = rs.getString("bookname");
                txtbookname.setText(BookName);
               
                String issueID = rs.getString("issuedate");
                txtissue.setText(issueID);
                String DueDate = rs.getString("duedate");
                dueid.setText(DueDate);
                
                
         
            }
            
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_bookidPopupMenuWillBecomeInvisible

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
          try
        {
            stmp = con.createStatement();
            String bookID = bookid.getSelectedItem().toString();
            String StID = stid.getText();
            //String IssuDate = issue
            //String returnBook = "YES";
           
            String query = "UPDATE issuebook SET returnbook='YES' WHERE bookid=? and studentid=? ";
          
            PreparedStatement prepareStmp = con.prepareStatement(query);
            
            
            prepareStmp.setString(1, bookID);
            prepareStmp.setString(2, StID);
            
            
           
            
            prepareStmp.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "The Book has Returned !!");
            
            
        
        }
        catch(Exception e)
        {
            
            System.out.print(e);
        
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookid;
    private javax.swing.JTextField dueid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField stid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtissue;
    // End of variables declaration//GEN-END:variables
}
